---
# tasks file for radarr
- name: Create radarr programdata dir
  win_file:
    path: 'C:\ProgramData\Radarr'
    state: directory

- name: Copy nzbdrone.db
  win_copy:
    src: nzbdrone.db
    dest: C:\ProgramData\Radarr\nzbdrone.db

- name: Copy config.xml
  win_copy:
    src: config.xml
    dest: C:\ProgramData\Radarr\config.xml

- name: Install radarr
  win_chocolatey:
    name: radarr
    state: present
