var lang = "en-US";
var mo = {};
mo["en-US"] = {
	"设为喜爱曲目": "Last.fm Love Track", //command
	"从喜爱曲目中删除": "Last.fm Unlove Track", //command
	"重置播放次数": "Reset Playcount", //command
	"刷新播放次数": "Refresh Playcount", //command
	"播放统计信息/等级/5": "Playback Statistics/Rating/5", //command
	"播放统计信息/等级/<不设置>": "Playback Statistics/Rating/<not set>", //command
	"视图/ELPlaylist/显示正在播放": "View/ELPlaylist/Show now playing", //command

	"Last.fm": "Last.fm",
	"未安装 \"foo_customdb\" 插件。": "The foo_customdb component is not installed.",
	"未设置 Last.fm 账户。": "Please set your Last.fm account.",
	"未设置 Last.fm API Key 或 secret。": "Please set your Last.fm API Key / Secret.",
	"与 Last.fm 服务器连接时发生错误。": "Unable to connect to Last.fm web services.",
	"未知错误。": "Unkonwn Error.",
	"HTTP 错误: ": "HTTP Error: ",
	"返回信息：": "Return message: ",
	"数据导入": "Import Your Last.fm Library",
	"从 Last.fm 下载数据并导入": "Download Data from Last.fm and Import It",
	"导入已下载的数据": "Import Downloaded Data",
	"自动更新时使用 Last.fm 拼写更正": "Use Last.fm Auto-Correct",
	"自动设为喜爱曲目": "Automatically Love Tracks",
	"关闭": "Off",
	"开启": "On",
	"设置规则...": "Condition...",
	"设置 Last.fm 账户": "Set Your Last.fm Account",
	"重新设置 Last.fm 账户": "Reset Your Last.fm Account",
	"账户设置成功。": "Success.",
	"控制台输出": "Debug",
	"属性": "Properties",
	"配置...": "Configure...",
	"在这里设置的标题格式化的结果等于 1 时将自动设为喜爱曲目。\n\n例如：\n\n$ifequal(%rating%,5,1,0)": "The result of the title formatting set here must equal 1 for a track to be automatically loved.\n\nExample:\n\n$ifequal(%rating%,5,1,0)",
	"文件": "File",
	"编辑": "Edit",
	"视图": "View",
	"播放": "Playback",
	"媒体库": "Library",
	"帮助": "Help",
	"正在播放": "Now Playing",
	"打开你的 Last.fm 个人专页": "Visit Your Last.fm User Profile Page",
	"无法打开你的默认浏览器。": "Unable to launch your default browser.",
	"正在连接 Last.fm，准备发送正在收听的曲目「%1$s」的「%2$s」...": "Connecting to Last.fm...\nReady to send now playing track information to Last.fm. (\"%2$s\" by \"%1$s\")",
	"向 Last.fm 发送正在收听的曲目「%1$s」的「%2$s」时发生错误，%3$s 秒后将重试。\n返回信息：%4$s": "Send now playing track information to Last.fm failed. Will retry after %3$s seconds. (\"%2$s\" by \"%1$s\")\nReturn message: %4$s",
	"向 Last.fm 发送正在收听的曲目「%1$s」的「%2$s」时遇到网络问题，%3$s 秒后将重试。\n返回信息：%4$s": "Send now playing track information to Last.fm failed because network error. Will retry after %3$s seconds. (\"%2$s\" by \"%1$s\")\nReturn message: %4$s",
	"向 Last.fm 发送正在收听的曲目「%1$s」的「%2$s」成功。": "Send now playing track information to Last.fm success. (\"%2$s\" by \"%1$s\")",
	"上一个向 Last.fm 发送 Scrobble 的操作尚未结束，%s 秒后将重试。": "Sending previous Scrobble to Last.fm... Will retry after %s seconds.",
	"向 Last.fm 发送 Scrobble...": "Sending Scrobble to Last.fm...",
	"向 Last.fm 发送 Scrobble 时发生错误，%1$s 秒后将重试。\n返回信息：%2$s": "Send Scrobble to Last.fm failed. Will retry after %1$s seconds.\nReturn message: %2$s",
	"向 Last.fm 发送 Scrobble 成功。": "Send Scrobble to Last.fm success.",
	"向 Last.fm 发送 Scrobble 时遇到网络问题，%1$s 秒后将重试。\n返回信息：%2$s": "Send Scrobble to Last.fm failed because network error. Will retry after %1$s seconds.\nReturn message: %2$s",
	"正在连接 Last.fm，准备将「%1$s」的「%2$s」设为喜爱曲目...": "Connecting to Last.fm...\nReady to Love Track... (\"%2$s\" by \"%1$s\")",
	"从 Last.fm 上将「%1$s」的「%2$s」成功设为喜爱曲目。": "Love Track success. (\"%2$s\" by \"%1$s\")",
	"从 Last.fm 上将「%1$s」的「%2$s」设为喜爱曲目失败。": "Love Track failed. (\"%2$s\" by \"%1$s\")",
	"正在连接 Last.fm，准备将「%1$s」的「%2$s」从喜爱曲目中删除...": "Connecting to Last.fm...\nReady to Unlove Track... (\"%2$s\" by \"%1$s\")",
	"从 Last.fm 上将「%1$s」的「%2$s」成功从喜爱曲目中删除。": "Unlove Track success. (\"%2$s\" by \"%1$s\")",
	"从 Last.fm 上将「%1$s」的「%2$s」从喜爱曲目中删除失败。": "Unlove Track failed. (\"%2$s\" by \"%1$s\")",
	"正在连接 Last.fm，准备同步正在收听曲目的「%1$s」的「%2$s」的统计信息...": "Connecting to Last.fm...\nReady to sync now playing track. (\"%2$s\" by \"%1$s\")",
	"同步曲目「%1$s」的「%2$s」的统计信息时发生错误。\n返回信息：%3$s": "Sync track failed. (\"%2$s\" by \"%1$s\")\nReturn message: %3$s",
	"同步曲目「%1$s」的「%2$s」的统计信息时发生错误，艺术家或曲目不存在。": "Sync track failed beacuse artist/track not found. (\"%2$s\" by \"%1$s\")",
	"同步曲目「%1$s」的「%2$s」的统计信息时发生错误。\n返回信息：%3$s": "Sync track failed. (\"%2$s\" by \"%1$s\")\nReturn message: %3$s",
	"未同步曲目「%1$s」的「%2$s」的统计信息，没有发现数据变动。": "Sync track aborted beacuse no changes found. (\"%2$s\" by \"%1$s\")",
	"同步正在收听曲目的「%1$s」的「%2$s」的统计信息成功。（播放次数）": "Sync now playing track success. (Love) (\"%2$s\" by \"%1$s\")",
	"同步正在收听曲目的「%1$s」的「%2$s」的统计信息成功。（喜爱曲目）": "Sync now playing track success. (Playcount) (\"%2$s\" by \"%1$s\")",
	"导入已终止。": "Import aborted.",
	"此问题与 Last.fm 服务器有关，请稍后重试。\n\n%s": "There is a problem with the Last.fm web services. Please try again later.\n\n%s",
	"已完成 %1$s/%2$s 页（喜爱曲目）": "Completed page %1$s of %2$s (loved tracks)",
	"已完成 %1$s/%2$s 页（播放次数）": "Completed page %1$s of %2$s (playcount)",
	"喜爱曲目下载失败页数：%s（每页包含 200 个曲目）": "Loved track page errors: %s (200 records are lost for every page that fails)",
	"播放次数下载失败页数：%s（每页包含 100 曲目）": "Playcount page errors: %s (100 records are lost for every page that fails)",
	"单个曲目处理失败数：%s": "Individual errors: %s",
	"导入操作将重启 foobar2000，确定要继续吗？": "Are you sure you want to import your Last.fm library to your foobar2000?\nThis action will restart your foobar2000.",
	"用户名": "Username",
	"密码（不保存）": "Password (will not be saved)",
	"自动将当前播放曲目设为喜爱曲目...": "Automatically love now playing track...",
	"无曲目": "No Track",
	"网络错误，请稍后重试。\n\n%s": "Network error. Please try again later.\n\n%s",
	"下载数据可能会花费一些时间，并且不会提示进度，请耐心等候。\n确定要继续吗？": "The data download may take some time to complete so please be patient, and the download progress will not be displayed.\nAre you sure to continue?",
	"数据下载完成，要导入吗？\n此操作将重启 foobar2000。": "The data download completed, are you sure to import it?\nThis action will restart your foobar2000.",
	"从 Last.fm 下载插图": "Download Artwork from Last.fm",
	"下载艺术家图片": "Download Artist Picture",
	"下载封面图片": "Download Album Cover",
	"没有图片可供下载。": "There is no picture to download.",
	"下载失败。\n返回信息：%s": "Download failed.\nReturn message: %s",
	"图片 %s 下载完成，文件保存在曲目所在文件夹。\n是否打开文件夹？": "The picture \"%s\" download completed, it's saved in current playing track's folder.",
	"文件已存在，是否继续下载并覆盖？": "The file exists. are you sure to continue and override it?",
	"保存二进制文件失败：\n%s": "Save binary file failed:\n%s",
	"保存文本文件失败：\n%s": "Save text file failed:\n%s"
}
